export const UserActionTypes = {
        ShowLogInModal: '[User] Show Log In Modal',
        HideLogInModal: '[User] Hide Log In Modal',
        LogIn: '[User] Log In',
        LogInFailure: '[User] Log In Failure',
        LogInSuccess: '[User] Log In Success',
        SignUp: '[User] Sign Up',
        SignUpFailure: '[User] Sign Up Failure',
        LogOut: '[User] Log Out',
        ResetPassword: '[User] Reset Password',
        ResetPasswordFailure: '[User] Reset Password Failure',
        ResetPasswordSuccess: '[User] Reset Password Success',
        ToggleUpdatePasswordForm: '[User] Toggle Update Password Form',
        UpdatePassword: '[User] UpdatePassword',
        UpdatePasswordFailure: '[User] Update Password Failure',
        UpdatePasswordSuccess: '[User] Update Password Success',
        ToggleUpdatePhotoUrl: '[User] Toggle Update Photo Url',
        UpdatePhotoUrl: '[User] Update Photo Url',
        UpdatePhotoUrlFailure: '[User] Update Photo Url Failure',
        UpdatePhotoUrlSuccess: '[User] Update Photo Url Success',
        ShowUpdateEmailForm: '[User] Show Update Email Form',
        HideUpdateEmailForm: '[User] Hide Update Email Form',
        ToggleUpdateEmailForm: '[User] Toggle Update Email Form',
        UpdateEmail: '[User] Update Email',
        UpdateEmailSuccess: '[User] Update Email Succsess',
        UpdateEmailFailure: '[User] Update Email Failure',
        SendEmailVerification: '[User] Send Email Verification',
        SendEmailVerificationSuccess: '[User] Send Email Verification Success',
        SendEmailVerificationFailure: '[User] Send Email Verification Failure'
};
